packages:
  - Samples/Idler/Backend/Dashboard
  - Samples/HelloNFT/Backend/Dashboard
  - Samples/CollectibleCardGame/Backend/Dashboard
  - Samples/TableStakes/Backend/Dashboard
  - MetaplaySDK/Frontend/*

allowBuilds:
  '@parcel/watcher': true
  bootstrap-vue: true
  esbuild: true
