<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>Latest</LangVersion>
    <RootNamespace>Game.Cloud</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(SharedCodePath)\**\*.cs" LinkBase="SharedCode" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(MetaplayServerPath)\Cloud\Metaplay.Cloud.csproj" />
  </ItemGroup>
</Project>
