# Options specifically for Idler's 'quickly' environment.

GooglePlayStore:
  EnableGoogleAuthentication: true
  GooglePlayApplicationId: example-project-idler
  GooglePlayOAuth2ClientCredentialsPath: kube-secret://user-google-oauth#json
  
WebLogin:
  Clients:
    "UnityWebGL":
      Scopes: "game.session"
      AllowedRedirectUrls: "https://lovely-wombats-build-quickly-assets.p1.metaplay.io/"

ClientConnection:
  CommitIdCheckRule: OnlyIfDefined
